/* Generated By:JavaCC: Do not edit this line. CommandParserConstants.java */
package de.uniba.wiai.lspi.util.console.parser;

public interface CommandParserConstants {

  int EOF = 0;
  int PARAMSTART = 5;
  int WORD = 6;
  int LETTER = 7;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"-\"",
    "<WORD>",
    "<LETTER>",
  };

}
